### ISSUE TITLE
Albums missing

### ISSUE THREAD

**Issue by Flashpok** [NEDb-tk/deemix-foobar2000#2]
Hi (again :-) ),

With a list of 50 albums, 15 are missing. 
Is it possible to display in console (or in link txt) the list of "artist/album" are missing ?

**Comment by NEDb-tk** [comment]
Strange... Maybe Deezer is having trouble finding certain albums. Ill look into it rn.

**Comment by Flashpok** [comment]
I try this code (main.py), adding urllib.parse.quote function : (I'm a newbie, sorry...) It's not perfect but it seems to help : 

```
      separate = '{}'.format(line.strip()).replace(' ', ' ').replace('-', ' ').replace('/', ' - ').replace(
        '_', ' ').replace('!', '').replace("'", ' ').replace('(', '').replace(')', '').replace('ö', 'o').replace('é', 'e').replace('è', 'e').replace('à', 'a').replace('ú', 'u')

    cleanencoding = urllib.parse.quote(separate.strip())

    #print(line.strip())
    print(separate)
    print(cleanencoding)

    content = urllib.request.urlopen(
        'https://api.deezer.com/search/album/?q={0}&index=0&limit=1&output=xml'.format(cleanencoding))
```

Perhaps, more clean code ? :-)

**Comment by Flashpok** [comment]
For example, in my foobar.txt list, there is this line "Björk - Medúlla". But some characters broke research and result in deezer website (research). If I replace by "Björk - Medulla", it works. I don't know if I must manually clean these characters, or if there is more clean solution.

**Comment by NEDb-tk** [comment]
Thanks, I will begin to implement these new additions to `main.py`.

**Comment by NEDb-tk** [comment]
Updated `main.py` with `unidecode`. Currently working on the other issue.
