### ISSUE TITLE
How better to target the result ?

### ISSUE THREAD

**Issue by Flashpok** [NEDb-tk/deemix-foobar2000#3]
For example, for line "Björk - Vespertine", it select the wrong album "Björk: Vespertine - A Pop Album as an Opera (Live)". I want to select (second result in deezer search) : "Vespertine" (artist: Björk). How exclude results that are not in foobar.txt line, in my example : "- A Pop Album as an Opera (Live)". perhaps impossible?

**Comment by Flashpok** [comment]
perhaps useful: in deezer API, it's possible to transform the name of the artist (information at the left of slash in foobar.txt line) by his ID : 

`artist['id']
    url = f"https://api.deezer.com/artist/{artist_id}/albums"
`
it would limit the scope of the research (only album). In my previous example, perhaps it would explude the result : "Björk: Vespertine - A Pop Album as an Opera (Live)" because Björk is not the artist of this album.

**Comment by Flashpok** [comment]
it seems more easy : 

`artist:"Björk" album:"Vespertine"`

Can you adapt the code and extract theses informations ? In the foobar.txt, "artist" is at the left of the slash and "album" at the right.
It would be fantastic !

**Comment by Flashpok** [comment]
perhaps the easy way is : 

Original line in foobar.txt : "Björk/Vespertine"
In your code, to delete : 
`replace('/', '  ')`
and add a prefixe : 
`artist:"`
and a suffixe: 
`"`
and replace : 
`replace('/', '" album:"')`

It seems to work ! Can you confirm ?

**Comment by NEDb-tk** [comment]
I can confirm and update `main.py` in a few. Thank you very much for further development!

**Comment by NEDb-tk** [comment]
<img src="https://raw.githubusercontent.com/NEDb-tk/deemix-foobar2000/main/images/search.PNG">

I see what ur saying, Ill get right onto it.

**Comment by NEDb-tk** [comment]
I modified the script to use Advanced Search (`album:"!!!"%20artist:"Thr!!!er"`). I have gotten mixed results. For albums like the one mentioned above, Deezer cannot seem to find it. So, I created another `if else` statement that should fix things. Basically, if Deezer cannot find the album with `album:""%20artist:""`, it'll resort/fallback to the old method of searching. And if it still can't find it, it'll let you know with: `No Result For: {}` in the terminal and the `links.txt` file.

**Comment by Flashpok** [comment]
thank you it works !
Script stops if there is a ','. If I replace by a " " it works !

**Comment by Flashpok** [comment]
I added a text distinction between 2 methods (because the second method have more false positives), line 52 :
`					links.write(' +-+-+-+-+-+ Less strict method +-+-+-+-+' + link + ' - ' + title + '\n')
`

**Comment by Flashpok** [comment]
almost results use more precise method (artist:"" album:"" search). Fantastic !!!

**Comment by NEDb-tk** [comment]
> 
> 
> I added a text distinction between 2 methods (because the second method have more false positives), line 52 :
> ` links.write(' +-+-+-+-+-+ Less strict method +-+-+-+-+' + link + ' - ' + title + '\n') `

Thanks, Ill add these and `.replace(',', ' ')`
