### ISSUE TITLE
To display (in a file or console) a "No result for ARTIST/ALBUM" if no match with Deezer API

### ISSUE THREAD

**Issue by Flashpok** [NEDb-tk/deemix-foobar2000#4]

**Comment by NEDb-tk** [comment]
Ill begin working on all these features/issues. Thank you for your contributions!

**Comment by NEDb-tk** [comment]
Added `If else` statement.

**Comment by Flashpok** [comment]
line 34 : 

missing a '\n' : 
`links.write('No Result For: {}'.format(line.strip()) +'\n')`
