### ISSUE TITLE
Best method for characters problems (no result in deezer for some albums)

### ISSUE THREAD

**Issue by Flashpok** [NEDb-tk/deemix-foobar2000#5]
Instead : 

```
separate = '{}'.format(line.strip()).replace(' ', ' ').replace('-', ' ').replace('/', ' - ').replace(
        '_', ' ').replace('!', '').replace("'", ' ').replace('(', '').replace(')', '').replace('ö', 'o').replace('é', 'e').replace('è', 'e').replace('à', 'a').replace('ú', 'u')
```

I test another method and more results display with deezer API : 

Add :  

`from unidecode import unidecode`

([Unidecode 1.2.0](https://pypi.org/project/Unidecode/) )

and add a "unaccented_string" variable instead "replace" function :

`   unaccented_string = unidecode(line.strip())`
 
and link with 'encode' variable : 

   ` encode = urllib.parse.quote(unaccented_string.strip())`

**Comment by NEDb-tk** [comment]
Just updated `main.py` with `No Result For: {}`. I too am a novice in web scraping, so I had no idea [this ](https://pypi.org/project/Unidecode/)existed! I will implement it shortly.

**Comment by NEDb-tk** [comment]
Updated `main.py` with it. I will soon update the readme. Thanks
