### ISSUE TITLE
How to accelerate firsts text processes ?

### ISSUE THREAD

**Issue by Flashpok** [NEDb-tk/deemix-foobar2000#6]
Hi,

Actually, I must make operations in text editor for preparing clean line "Björk/Vespertine".

Foobar2000 gives me -at the end of his analyse text file-  this line (not album but several tracks of album, for this reason it's better to re-download the album, not specific tracks) : 

For example : 

`"Björk/Verspertine/01 - Hidden Place.flac"
"Björk/Verspertine/02 - Cocoon.flac"`

Is it possible to transform these line in this only one  : 

"Björk/Verspertine"

Step 1 : to tranform : 
`"Björk/Verspertine/01 - Hidden Place.flac"
"Björk/Verspertine/02 - Cocoon.flac"`

to : 
`Björk/Verspertine
Björk/Verspertine`

Step 2 : Keep only one line for same albums : 

`Björk/Verspertine`

Sometimes there is subfolders (CD1 or CD2, etc) : 
`"Björk/Verspertine/CD3/01 - Hidden Place.flac"`

If subfolder: 
Keep only text after the the first slash. Delete second slash et text at his right.

Or economic solution, keep "CD1" if it's possible to target it with Advanced search in deezer ? 

Is it possible to make this ?

**Comment by Flashpok** [comment]
Perhaps, it would be interesting to target only tracks ? It would be more economic ? But perhaps many files would be no find in advanced research. What do you think about that ?

**Comment by Flashpok** [comment]
ho yes, it seems to work : 

artist:"Björk" album:"Vespertine" track:"Hidden Place"

But perhaps it makes more errors ? (confusions between albums with same track, for examples "Live" albums or "remaster" albums). And I don"t know how target CD number if there are more than one CD in the album. :-)

**Comment by NEDb-tk** [comment]
I will take a look in a few minutes. Thanks for your patients

**Comment by Flashpok** [comment]
"Or economic solution, keep "CD1" if it's possible to target it with Advanced search in deezer ?"
I check and I don't think it's possible. Can you confrm ?

**Comment by NEDb-tk** [comment]
Yes, CD1 is possible.
>


disk_number | The track's album's disk number
-- | --




On the Deezer API

**Comment by Flashpok** [comment]
how, fantastic ! So its possible to download only tracks corrupted ?

**Comment by Flashpok** [comment]
One foobar2000 location example (with CD number) :
`"D'Angelo/Brown Sugar (Deluxe Edition)/CD1/01 - Brown Sugar.flac"`

for
`Artist/album/CD Number, Track Number, Title`

It would be so useful to download only buggy tracks (without errors)

**Comment by NEDb-tk** [comment]
I'm working on a solution now. Ill keep u updated!

**Comment by NEDb-tk** [comment]
With `outfile.write(line.replace('"', '').replace(' - ', '/').replace('.flac', ''))`,
This: `"D'Angelo/Brown Sugar (Deluxe Edition)/CD1/01 - Brown Sugar.flac"`
To: `D'Angelo/Brown Sugar (Deluxe Edition)/CD1/01/Brown Sugar`
I'm working on creating CD1 vars for Advanced Search.

**Comment by Flashpok** [comment]
Actually, in text editor I use this grep, to select all album with a  "CD" number.

`(.*/).(.*/).(.*/)`

I don't know if it can help :-)

**Comment by NEDb-tk** [comment]
Went under a complete renovation! I am happy to announce that, you can now search for individual tracks! And you don't have to manually clean the foobar output file anymore. 
`strip.py`:
>"D'Angelo/Brown Sugar (Deluxe Edition)/CD1/01 - Brown Sugar.flac"
>D'Angelo/Brown Sugar (Deluxe Edition)/CD1/01/Brown Sugar

`main.py`:
>D'Angelo/Brown Sugar (Deluxe Edition)/CD1/01/Brown Sugar (from `strip.txt`)
>D'Angelo/Brown Sugar (Deluxe Edition)/Brown Sugar
>Url

Ill update the README in a second.

**Comment by NEDb-tk** [comment]
Also, I cannot seem to find `Björk/Verspertine` for some reason. Even with the least strict search `https://api.deezer.com/search/album/?q=Bjo%CC%88rk%20Verspertine&index=0&limit=1&output=xml`. Maybe because it is a playlist? Ill think about implementing a playlist feature. Advanced Search has [this](https://developers.deezer.com/api/playlist).

**Comment by Flashpok** [comment]
Thank you ! 
I ll try this update now !
Sorry for "Verspertine". Mistake from me, replace bu "Vespertine" :-)

**Comment by Flashpok** [comment]
Yes, It works !
There is a mistake in results if track number is 00x. (In my foobar.txt file for example, one track is number 08, but after strop.py, it becomes 008. And I lose result the url link. If I edit the strip.txt and restore by "08", it works

**Comment by NEDb-tk** [comment]
Yes, this will be possible. I’ll update it in a bit.

**Comment by NEDb-tk** [comment]
Should be fixed. Ill keep this issue open awaiting your response. Thanks for all of your contributions!

**Comment by Flashpok** [comment]
1. Some problem with the limit of track_count (line 34)
`while track_count < 40:`

I set 120 et no more problems (with large albums)

2. Some problem with "/" in title. I add this line (line 50)

`title_no_slash = '{}'.format(title_ascii).replace('/', ' ')  #Remove "/" from title`

`title_uni = urllib.parse.quote(title_no_slash) #convert ASCII to Unicode`

**Comment by Flashpok** [comment]
I don't understand the difference between "Couldn't Find Album" and "Couldn't Find Track".
Results from "Couldn't Find Track" aren't inside "Couldn't Find Album" ?

**Comment by Flashpok** [comment]
the "001" problem seems not be resolved.

**Comment by NEDb-tk** [comment]
Strange... It seems to work on my side.

**Comment by Flashpok** [comment]
It seems good ! Thank you !

**Comment by NEDb-tk** [comment]
Great! Ill get onto the other issues.
