### ISSUE TITLE
To bypass Artist is no result

### ISSUE THREAD

**Issue by Flashpok** [NEDb-tk/deemix-foobar2000#9]
If track result is null, is it possible to make a new request without the artist variable ?
(sometimes, Deemix select an artist but it's not always the artist selected in adavanced research on deezer.

If track research have no result,
Than try new track research with album, (CD), track number, track name

What do you think about that ?

**Comment by NEDb-tk** [comment]
So, if `total == 0` and `'title_uni' uni in locals()`, then retry but instead search for the album rather than downloading the individual track?

**Comment by Flashpok** [comment]
yes, good idea (is it possible ton indicate that the request uses a second method ("no artist")) ?

**Comment by NEDb-tk** [comment]
Yes. On the retry (if all requirements are met) we just `print('Searching for Album Instead')`.

**Comment by NEDb-tk** [comment]
Updated!

**Comment by Flashpok** [comment]
I ll try today ! Thank you again !
